on:
  push:
    branch:
      - 'development'

jobs:
  - name: build mission scripts
    run: build_mission_scripts_release.sh

  - name: create release
    uses: actions/create-release@v1
    id: create_release
    env:
      GITHUB_TOKEN: ${{ github.token }}
    with:
      draft: false
      prerelease: false
      release_name: ${{ steps.version.outputs.version }}
      tag_name: ${{ github.ref }}
      body_path: release.zip

  - name: upload zip file
    uses: actions/upload-release-asset@v1
    env:
      GITHUB_TOKEN: ${{ github.token }}
    with:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      asset_path: build/mission_scripts.zip
      asset_name: mission_scripts.zip
      asset_content_type: application/gzip